#!/bin/zsh

cd "$(dirname "${BASH_SOURCE[0]}")"
BASE=$(pwd)

if [ -z $DOTFILES ]; then
  echo "setting \$DOTFILES in ~/.zshenv"
  echo "export DOTFILES=$BASE" >> ~/.zshenv
else
  echo "\$DOTFILES is already set to $DOTFILES. Aborting."
  exit 1
fi


ln -sfv vim ~/.vim
vim +PlugInstall +qall
ln -sfv zsh/zshrc ~/.zshrc
