#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"
BASE=$(pwd)

if [ -z $DOTFILES ]; then
  echo "setting \$DOTFILES in ~/.zshenv"
  echo "export DOTFILES=$BASE" >> ~/.zshenv
else
  echo "\$DOTFILES is already set to $DOTFILES. Aborting."
  exit 1
fi

ZSH=$BASE/zsh/omz RUNZSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# clone powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $BASE/zsh/omz/custom/themes/powerlevel10k

NVIM_CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/nvim
NVIM_DATA_DIR=${XDG_DATA_HOME:-$HOME/.local/share}/nvim

# T on Linux should be F on macOS
ln -sTfv $BASE/vim $HOME/.vim
ln -sTfv $BASE/nvim $NVIM_CONFIG_DIR
ln -sTfv $BASE/zsh/zshrc $HOME/.zshrc

mkdir -p $NVIM_DATA_DIR/site/autoload
cp $BASE/vim/autoload/plug.vim $NVIM_DATA_DIR/site/autoload/plug.vim

vim +PlugInstall +qall
nvim +PlugInstall +qall
