#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"
BASE=$(pwd)

if [ -z $DOTFILES ]; then
  echo "setting \$DOTFILES in ~/.zshenv"
  echo "export DOTFILES=$BASE" >> ~/.zshenv
else
  echo "\$DOTFILES is already set to $DOTFILES. Aborting."
  exit 1
fi

ZSH=$BASE/zsh/omz sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# F on macOS should be T on Linux
ln -sFfv $BASE/vim ~/.vim
ln -sFfv $BASE/zsh/zshrc ~/.zshrc

vim +PlugInstall +qall
